### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by nunojesus** [stefan50/ThePiano#2]
Hi, can you tell me more about this project? What it does?

Greetings

**Comment by stefan50** [comment]
Hi!

For now it is hard to say anything because the project is really early in its days, however, its idea is to be an RPG game (8-bit style), in which you use your MIDI controller to fight against enemies. Hardly does it work for now, but we are persistent it will in the foreseeable future.

Should you have any questions, do not hesitate to ask!

Best regards,
Stefan Angelov
